# Generated by Django 2.2 on 2019-04-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_av', '0005_video_fanart_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
