# Generated by Django 2.2 on 2019-04-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_av', '0010_auto_20190420_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='sample_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
