# Generated by Django 2.2 on 2019-04-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_av', '0011_video_sample_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
