# Generated by Django 2.2 on 2019-04-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_av', '0013_auto_20190426_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
