# Generated by Django 2.2 on 2019-05-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_av', '0014_auto_20190426_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_path',
            field=models.FilePathField(blank=True, null=True, unique=True),
        ),
    ]
