# Generated by Django 2.2 on 2019-05-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_av', '0015_video_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='plot',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
