# Generated by Django 2.2 on 2019-05-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_av', '0017_auto_20190515_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_path',
            field=models.FilePathField(default=''),
        ),
    ]
