# Generated by Django 2.2 on 2019-05-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_av', '0020_auto_20190515_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_path',
            field=models.CharField(max_length=500),
        ),
    ]
